/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:27796c0b-d1a9-455b-ad12-3d4efb6c5738",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_J5KHLBcMQ",
    "aws_user_pools_web_client_id": "4t8l4ck7ims2kmgno87kl8refn",
    "oauth": {
        "domain": "nextjsauthsystema60a5fa3-a60a5fa3-dev.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://aws-next-auth-system.vercel.app/,https://aws-next-auth-system.vercel.app/",
        "redirectSignOut": "https://aws-next-auth-system.vercel.app/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_login_mechanism": [
        "EMAIL"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    }
};


export default awsmobile;
